name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for making an issue! @Matt-Gleich will take a look as soon as possible'' first issue'
        pr-message: 'Thank you for making an pull request! @Matt-Gleich will take a look as soon as possible'' first pr'
